name: CI

on:

  push:
    branches:
      - main
    paths:
      - docs/**
      - .github/workflows/ci.yml

jobs:

  build-doc:
    name: Build documentation using sphinx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          repository: 'NaokiHori/SimpleInterpolator'
          ref: 'main'
      - name: Install Gnuplot
        run: sudo apt-get -y install gnuplot
      - name: Create eps and tex files
        run: |
          cd docs
          cp create_figures/gnuplot.sh .
          bash gnuplot.sh
      - name: Convert eps to pdf
        run: |
          cd docs
          cp create_figures/epstopdf.sh .
          docker run \
            --rm \
            --volume ${PWD}:/project \
            --workdir /project \
            naokihori/texlive:gnuplot-epslatex \
            /bin/sh epstopdf.sh
      - name: Compile tex files
        run: |
          cd docs
          cp create_figures/pdflatex.sh .
          docker run \
            --rm \
            --volume ${PWD}:/project \
            --workdir /project \
            naokihori/texlive:gnuplot-epslatex \
            /bin/sh pdflatex.sh
      - name: Build documentation using Sphinx
        run: |
          echo "cd docs && make html" > sphinx.sh
          docker run \
            --rm \
            --volume ${PWD}:/project \
            --workdir /project \
            sphinxdoc/sphinx:5.0.0 \
            /bin/bash sphinx.sh
      - name: Upload artifacts
        # upload everything under docs/build/html/
        uses: actions/upload-artifact@v3
        with:
          name: DocHTML
          path: docs/build/html

  publish-doc:
    name: Push artifacts to gh-pages branch
    runs-on: ubuntu-latest
    needs: build-doc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          repository: 'NaokiHori/SimpleInterpolator'
          ref: 'main'
      - name: Download artifacts
        # download to docs/
        uses: actions/download-artifact@v3
        with:
          name: DocHTML
          path: docs/
      - name: Commit documentation changes
        run: |
          git switch -c gh-pages
          cd docs/
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: "."
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          force: true

